//! CONFORMANCE.md renderer. Incomplete runs never print an overall rate.

use crate::{Report, RunStatus};
use netpay_grid_gen::OracleClass;
use std::fmt::Write as _;

pub fn render(report: &Report, methodology: &str) -> String {
    let mut out = String::new();
    out.push_str("# Conformance\n\n");
    out.push_str("Oracle is CRA PDOC (`https://apps.cra-arc.gc.ca/ebci/rhpd/beta/`).\n");
    writeln!(
        out,
        "PDOC version observed on filled vectors: `{}`.",
        report.pdoc_identity
    )
    .ok();
    writeln!(out, "Capture operator: {}.", report.harness_git_sha).ok();
    out.push('\n');
    out.push_str("Expected amounts are PDOC-only. They are never filled from the engine.\n");
    out.push('\n');
    out.push_str("This file is generated by `tools/conformance` (`netpay-conformance`).\n");
    out.push_str("Do not hand-edit rates or counts; change the run and regenerate.\n\n");

    match report.status {
        RunStatus::InProgress => {
            out.push_str("**Status: run in progress.** Defined PDOC cases remain unmeasured.\n");
            out.push_str("This document states n, measured, and pending. It does **not**\n");
            out.push_str("compute an overall agreement rate.\n\n");
        }
        RunStatus::Complete => {
            if let Some(rate) = &report.agreement_rate {
                writeln!(
                    out,
                    "**Overall agreement rate (PDOC corpora): `{rate}`.**\n"
                )
                .ok();
            }
        }
    }

    out.push_str("## Methodology\n\n");
    out.push_str(methodology);
    out.push('\n');

    out.push_str("## Sampling design\n\n");
    out.push_str("Published PDOC queue: every **distinct** July live-edition boundary\n");
    out.push_str("form the salary UI can enter — **ten** of fourteen legal P, both claim\n");
    out.push_str("codes, fingerprint-deduped. The earlier **15,264** figure assumed all\n");
    out.push_str("fourteen P; PDOC cannot capture annual / semi-annual / quarterly /\n");
    out.push_str("hourly (`1`, `2`, `4`, `2000`). Those forms, plus `$0` and sub-dollar\n");
    out.push_str("gross, are the named **`uncapturable`** class below — validated by\n");
    out.push_str("invariants and the differential oracle (same as the interior ladder),\n");
    out.push_str("not by silently shortening a queue that still claims 15,264.\n\n");
    out.push_str("The spec’s “250,000 cases” target is a case *list*, not a PDOC queue.\n");
    out.push_str("At 3 seconds per uncached form, that queue does not finish. The adopted\n");
    out.push_str("split is: **every capturable unique live-edition boundary form goes to\n");
    out.push_str("PDOC; the interior log-ladder and the uncapturable class do not.**\n\n");
    out.push_str("| | |\n|--|--|\n");
    writeln!(out, "| grid_version | `{}` |", report.grid_version).ok();
    writeln!(out, "| grid cells | {} |", report.sampling.grid_cases).ok();
    writeln!(
        out,
        "| unique July boundary forms, all 14 legal P (superseded) | {} |",
        report.sampling.unique_form_boundary_july_all_legal_p
    )
    .ok();
    writeln!(
        out,
        "| **PDOC queue (10 capturable P, distinct after dedup)** | **{}** |",
        report.sampling.unique_form_boundary_july
    )
    .ok();
    writeln!(
        out,
        "| unique July uncapturable forms | {} |",
        report.sampling.unique_form_boundary_july_uncapturable
    )
    .ok();
    writeln!(
        out,
        "| wall clock at 3 s / uncached form | {} |",
        report.sampling.hours_at_3s_july_boundary
    )
    .ok();
    writeln!(
        out,
        "| overnight 8 h capacity | {} |",
        report.sampling.overnight_8h_capacity
    )
    .ok();
    writeln!(
        out,
        "| log-ladder cells (invariants only) | {} |",
        report
            .sampling
            .by_class
            .get("log_ladder")
            .copied()
            .unwrap_or(0)
    )
    .ok();
    writeln!(
        out,
        "| DateBeforeCoverage cells (engine error) | {} |",
        report.sampling.unresolvable_as_of
    )
    .ok();
    out.push('\n');
    out.push_str("Grid cells collapse heavily onto PDOC fingerprints; the finished capture\n");
    out.push_str("count will be at most the distinct-form figure above (smoke already showed\n");
    out.push_str("cache hits from overlapping forms).\n\n");

    out.push_str("## Run conditions\n\n");
    out.push_str("| | |\n|--|--|\n");
    writeln!(out, "| grid_version | `{}` |", report.grid_version).ok();
    writeln!(
        out,
        "| engine_build_sha256 | `{}` |",
        report.engine_build_sha256
    )
    .ok();
    writeln!(
        out,
        "| rule_set_versions | `{}` |",
        report.rule_set_versions.join("`, `")
    )
    .ok();
    writeln!(out, "| rule_set_sha256 | `{}` |", report.rule_set_sha256).ok();
    writeln!(out, "| PDOC identity | `{}` |", report.pdoc_identity).ok();
    writeln!(out, "| browser | {} |", report.browser).ok();
    writeln!(out, "| harness | {} |", report.harness_git_sha).ok();
    writeln!(
        out,
        "| latest PDOC retrieved_at | `{}` |",
        report.latest_pdoc_retrieved_at
    )
    .ok();
    out.push('\n');

    out.push_str("## Cases by oracle class\n\n");
    out.push_str("Each grid cell is named with the oracle allowed to validate it.\n");
    out.push_str("Boundary cells that share a PDOC-visible fingerprint collapse to one\n");
    out.push_str("form; the queue size is the unique-form count above, not the cell count.\n\n");
    out.push_str("| Jurisdiction | P | Rule set | Oracle class | Cells |\n");
    out.push_str("|--|--|--|--|--|\n");
    for (shown, row) in report.census.iter().enumerate() {
        if shown == 24 {
            writeln!(
                out,
                "| … | … | … | … | {} more slices in `conformance.json` |",
                report.census.len().saturating_sub(24)
            )
            .ok();
            break;
        }
        let class = match row.oracle_class {
            OracleClass::Pdoc => "pdoc",
            OracleClass::Invariants => "invariants",
            OracleClass::Uncapturable => "uncapturable",
            OracleClass::EngineError => "engine_error",
        };
        writeln!(
            out,
            "| {} | {} | `{}` | {class} | {} |",
            row.jurisdiction, row.pay_period, row.rule_set_version, row.cells
        )
        .ok();
    }
    out.push('\n');
    out.push_str("Full slice table: [`conformance.json`](conformance.json) `census`.\n\n");

    out.push_str("## Corpora\n\n");
    for corpus in &report.corpora {
        writeln!(out, "### `{}`\n", corpus.id).ok();
        out.push_str("| | |\n|--|--|\n");
        writeln!(out, "| oracle class | `{}` |", corpus.oracle_class).ok();
        writeln!(out, "| defined | {} |", corpus.cases_defined).ok();
        writeln!(out, "| measured | {} |", corpus.cases_measured).ok();
        writeln!(out, "| pending | {} |", corpus.pending).ok();
        writeln!(out, "| exact matches | {} |", corpus.exact_matches).ok();
        match &corpus.agreement_rate {
            Some(rate) => writeln!(out, "| agreement rate | `{rate}` |").ok(),
            None if corpus.oracle_class == "invariants" || corpus.oracle_class == "uncapturable" => {
                writeln!(
                    out,
                    "| agreement rate | *not a PDOC corpus; invariants + differential oracle (§16.2), not per-cell PDOC* |"
                )
                .ok()
            }
            None => writeln!(
                out,
                "| agreement rate | *not computed (incomplete PDOC corpus)* |"
            )
            .ok(),
        };
        out.push('\n');
    }

    out.push_str("## Disagreements\n\n");
    let open: Vec<_> = report
        .corpora
        .iter()
        .flat_map(|c| c.disagreements.iter())
        .collect();
    if open.is_empty() {
        out.push_str("None open.\n\n");
    } else {
        out.push_str("| id | provincial_tax | federal_tax | cpp | net_pay |\n|--|--|--|--|--|\n");
        for d in &open {
            let cell = |k: &str| d.delta.get(k).map(String::as_str).unwrap_or("—");
            writeln!(
                out,
                "| `{}` | {} | {} | {} | {} |",
                d.id,
                cell("provincial_tax"),
                cell("federal_tax"),
                cell("cpp"),
                cell("net_pay")
            )
            .ok();
        }
        out.push('\n');
        out.push_str("Full request / engine / PDOC maps: [`conformance.json`](conformance.json) `corpora[].disagreements`.\n\n");
        for d in open {
            writeln!(out, "### `{}`\n", d.id).ok();
            writeln!(out, "{}\n", d.explanation).ok();
        }
    }

    out.push_str("### Closed — D-007 biweekly mid-year K2\n\n");
    out.push_str("**Vector:** `on-biweekly-midyear-k2-max` (matches under `pdoc_observed`).\n");
    out.push_str("Published as **M-002**. PDOC does not force `base_max` in the reaching\n");
    out.push_str("period. That is a fact about PDOC, stated with inversion in\n");
    out.push_str("[findings/001](docs/findings/001-k2-maximum-in-reaching-period.md).\n\n");

    out.push_str("### Open — M-003 PDOC midpoint direction\n\n");
    out.push_str("Live disagreement (counts in the rate). T4127 half-up at a midpoint\n");
    out.push_str("goes up; PDOC is sometimes 1¢ lower. Not Alberta-specific (AB is dense).\n");
    out.push_str("Finished July queue: 164 one-cent disagreements (counted in the rate) and\n");
    out.push_str("780 step-2 non-advances (named, not in the rate). Condition unnamed.\n");
    out.push_str("`rounding_compat: pdoc` is a typed error\n");
    out.push_str("([ADR-003](docs/ADR-003-rounding-compat.md)).\n");
    out.push_str("[findings/002](docs/findings/002-pdoc-midpoint-direction.md).\n\n");

    out.push_str("## Cases where PDOC is believed wrong\n\n");
    out.push_str("None settled. M-003 is an open PDOC midpoint-direction delta — not a declared PDOC error.\n");
    out.push_str("M-002 remains a selectable `k2_method` difference under the default.\n\n");

    out.push_str("## Coverage gaps\n\n");
    for gap in &report.coverage_gaps {
        writeln!(out, "- {gap}").ok();
    }
    out.push('\n');

    out.push_str("## M1 measured results (complete corpus)\n\n");
    out.push_str("Ontario 2026-01, twenty vectors, operator manual, PDOC `2026-06-11`.\n");
    out.push_str(
        "All twenty match. See `crates/netpay-core/tests/vectors/pdoc_ontario_2026_01.json`.\n\n",
    );

    out.push_str("## M2 exit checklist\n\n");
    out.push_str("| Criterion | State |\n|--|--|\n");
    out.push_str(
        "| Ingest round-trips to hand-authored Ontario and federal files | yes (test 6) |\n",
    );
    out.push_str("| Thirteen jurisdictions, both 2026 editions, test 28 and 28b | yes |\n");
    out.push_str("| July delta overlay; ten unchanged jurisdictions byte-identical | yes |\n");
    out.push_str("| BC/NL/PE OptionScoped proration on both options | yes |\n");
    out.push_str("| 2026-06-30 / 2026-07-01 boundary pair BC, NL, PE, ON | yes |\n");
    out.push_str("| Quebec typed unsupported, never federal-only | yes |\n");
    out.push_str("| Grid deterministic, versioned, boundary-present, even | yes (`2026.1`) |\n");
    out.push_str(
        "| Oracle sampling design decided, public, finishable | **yes** (this section) |\n",
    );
    out.push_str(
        "| Conformance report with the real number and every disagreement | **this file** |\n",
    );
    out.push_str("| Findings 001 (K2) and M-001 discontinuity written up | yes |\n");
    out.push_str("| Tagged `v0.3.0-m2` | after this report is committed |\n\n");

    out.push_str("## M0 arithmetic canaries\n\n");
    out.push_str("- `truncate_exemption_to_cent(3500/12) == 291.66`\n");
    out.push_str("- Twin: `round_contribution_to_cent` on the same input is `291.67`\n");
    out.push_str("- `./scripts/float-ban.sh` clean\n");
    out
}
