//! Sampling design for oracle contact (spec Step 6).
//!
//! The full grid is a case *list*. PDOC is a rate-limited human calculator.
//! This module classifies cells so CONFORMANCE.md can name, per class, which
//! oracle validated them — and so we never queue a run that cannot finish.

use crate::{Grid, GridCase};
use serde::Serialize;
use std::collections::{BTreeMap, BTreeSet};
use takehome_core::rules::loader::EMBEDDED_REGISTRY;
use takehome_core::rules::schema::CalendarDate;

/// Which validator is allowed to speak for a cell.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum CaseClass {
    /// Bracket / YMPE / YAMPE / BPA / surtax / health / BC S / bonus ±0.01.
    Boundary,
    /// Log-spaced interiors only. Not a PDOC queue item.
    LogLadder,
    /// Rule-set date anchors with no other boundary. Collapses in PDOC.
    DateAnchor,
}

/// PDOC-visible fields. `as_of`, `k2_method`, and `targets` are not on the form.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Serialize)]
pub struct PdocFingerprint {
    pub province: String,
    pub pay_period: u16,
    pub gross_pay: String,
    pub calculation_option: String,
    pub bonus: Option<String>,
    pub federal_claim_code: u8,
    pub provincial_claim_code: u8,
}

/// Counts for grid `2026.1`. Regenerated by `takehome-grid-gen --report`.
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct SamplingReport {
    pub grid_version: String,
    pub grid_cases: u64,
    pub by_class: BTreeMap<String, u64>,
    pub unresolvable_as_of: u64,
    pub resolvable: u64,
    pub boundary_resolvable: u64,
    pub unique_form_all_resolvable: u64,
    pub unique_form_log_resolvable: u64,
    pub unique_form_boundary_ignoring_as_of: u64,
    pub unique_form_boundary_with_rule_set: u64,
    pub unique_form_boundary_january: u64,
    /// Superseded design: July unique forms across all fourteen legal P.
    pub unique_form_boundary_july_all_legal_p: u64,
    /// Published PDOC queue: July unique forms against the ten capturable P
    /// (excludes `$0` / sub-dollar gross). Fingerprint-deduped.
    pub unique_form_boundary_july: u64,
    /// July unique forms that cannot be entered on the live PDOC salary form.
    pub unique_form_boundary_july_uncapturable: u64,
    pub unique_form_boundary_july_claim1: u64,
    pub unique_form_boundary_july_claim1_common_p: u64,
    pub unique_form_boundary_july_by_province: BTreeMap<String, u64>,
    pub hours_at_3s_full_grid: String,
    pub hours_at_3s_unique_form_all: String,
    pub hours_at_3s_unique_boundary_form: String,
    pub hours_at_3s_july_boundary: String,
    pub hours_at_3s_july_boundary_claim1: String,
    pub hours_at_3s_july_boundary_claim1_common_p: String,
    pub overnight_8h_capacity: u64,
    pub cache_records_on_disk: u64,
    pub notes: Vec<String>,
}

/// Which oracle is allowed to speak for a cell. Published in CONFORMANCE.md.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum OracleClass {
    /// Capturable live-edition boundary form. PDOC is the validator.
    Pdoc,
    /// Log-ladder interiors and date anchors. Engine invariants only.
    Invariants,
    /// Boundary forms the live PDOC salary UI cannot enter (P ∈ {1,2,4,2000},
    /// `$0` / sub-dollar gross). Invariants + differential oracle — same as
    /// the interior ladder — not a silently shorter PDOC queue.
    Uncapturable,
    /// `DateBeforeCoverage` and similar. Engine error path, not a form.
    EngineError,
}

/// Pay periods the live PDOC salary form exposes (Appendix P). Ten of fourteen.
pub const PDOC_CAPTURABLE_PAY_PERIODS: &[u16] = &[10, 12, 13, 22, 24, 26, 27, 52, 53, 240];

/// Legal P values with no salary-form control. Validated as [`OracleClass::Uncapturable`].
pub const PDOC_UNCAPTURABLE_PAY_PERIODS: &[u16] = &[1, 2, 4, 2000];

/// True when the form can be filled on live PDOC (capturable P and non-trivial gross).
pub fn is_pdoc_capturable_form(pay_period: u16, gross_pay: &str) -> bool {
    PDOC_CAPTURABLE_PAY_PERIODS.contains(&pay_period)
        && gross_pay != "0.00"
        && !gross_pay.starts_with("0.")
}

/// Cell counts sliced the way spec §11.4 asks the report to name them.
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct CensusRow {
    pub jurisdiction: String,
    pub pay_period: u16,
    pub rule_set_version: String,
    pub oracle_class: OracleClass,
    pub cells: u64,
}

const COMMON_PAY_PERIODS: &[u16] = &[1, 12, 24, 26, 52, 53];

const BOUNDARY_PREFIXES: &[&str] = &[
    "federal_bracket:",
    "provincial_bracket:",
    "ympe:",
    "yampe:",
    "bpaf_phaseout:",
    "bpamb_phaseout:",
    "ontario_surtax:",
    "ontario_health_premium:",
    "bc_tax_reduction:",
    "bonus_shortcut:",
];

/// Classify one cell from its `targets`. Mixed tags: any boundary tag wins.
pub fn classify_case(case: &GridCase) -> CaseClass {
    if case.targets.iter().any(|t| is_boundary_target(t)) {
        return CaseClass::Boundary;
    }
    if case.targets.iter().any(|t| t.starts_with("log_ladder:")) {
        return CaseClass::LogLadder;
    }
    CaseClass::DateAnchor
}

pub fn is_boundary_target(target: &str) -> bool {
    BOUNDARY_PREFIXES.iter().any(|p| target.starts_with(p))
}

pub fn pdoc_fingerprint(case: &GridCase) -> PdocFingerprint {
    PdocFingerprint {
        province: case.province.clone(),
        pay_period: case.pay_period,
        gross_pay: case.gross_pay.clone(),
        calculation_option: case.calculation_option.clone(),
        bonus: case.bonus.clone(),
        federal_claim_code: case.federal_claim_code,
        provincial_claim_code: case.provincial_claim_code,
    }
}

fn resolve_edition(as_of: &str) -> Option<String> {
    let date: CalendarDate = as_of.parse().ok()?;
    EMBEDDED_REGISTRY
        .resolve(date)
        .ok()
        .map(|set| set.rule_set_version.clone())
}

fn class_key(class: CaseClass) -> String {
    match class {
        CaseClass::Boundary => "boundary".to_string(),
        CaseClass::LogLadder => "log_ladder".to_string(),
        CaseClass::DateAnchor => "date_anchor".to_string(),
    }
}

fn hours(n: u64) -> String {
    let secs = n.saturating_mul(3);
    format!("{}h {}m", secs / 3600, (secs % 3600) / 60)
}

fn set_len(set: &BTreeSet<PdocFingerprint>) -> u64 {
    u64::try_from(set.len()).unwrap_or(0)
}

/// Build the sampling report for a generated grid.
pub fn sampling_report(grid: &Grid, cache_record_count: u64) -> SamplingReport {
    let mut by_class: BTreeMap<String, u64> = BTreeMap::new();
    let mut unresolvable = 0u64;
    let mut resolvable = 0u64;
    let mut boundary_resolvable = 0u64;
    let mut all_form: BTreeSet<PdocFingerprint> = BTreeSet::new();
    let mut log_form: BTreeSet<PdocFingerprint> = BTreeSet::new();
    let mut boundary_form: BTreeSet<PdocFingerprint> = BTreeSet::new();
    let mut boundary_with_edition: BTreeSet<(PdocFingerprint, String)> = BTreeSet::new();
    let mut january: BTreeSet<PdocFingerprint> = BTreeSet::new();
    let mut july_all: BTreeSet<PdocFingerprint> = BTreeSet::new();
    let mut july_pdoc: BTreeSet<PdocFingerprint> = BTreeSet::new();
    let mut july_uncapturable: BTreeSet<PdocFingerprint> = BTreeSet::new();
    let mut july_claim1: BTreeSet<PdocFingerprint> = BTreeSet::new();
    let mut july_claim1_common: BTreeSet<PdocFingerprint> = BTreeSet::new();
    let mut july_by_province: BTreeMap<String, BTreeSet<PdocFingerprint>> = BTreeMap::new();

    for case in &grid.cases {
        let class = classify_case(case);
        *by_class.entry(class_key(class)).or_insert(0) += 1;
        let edition = resolve_edition(&case.as_of);
        if edition.is_none() {
            unresolvable += 1;
            continue;
        }
        resolvable += 1;
        let fp = pdoc_fingerprint(case);
        all_form.insert(fp.clone());
        match class {
            CaseClass::Boundary => {
                boundary_resolvable += 1;
                let ed = edition.expect("checked");
                boundary_form.insert(fp.clone());
                boundary_with_edition.insert((fp.clone(), ed.clone()));
                if ed == "2026-01-01" {
                    january.insert(fp.clone());
                }
                if ed == "2026-07-01" {
                    july_all.insert(fp.clone());
                    if is_pdoc_capturable_form(case.pay_period, &case.gross_pay) {
                        july_pdoc.insert(fp.clone());
                        july_by_province
                            .entry(case.province.clone())
                            .or_default()
                            .insert(fp.clone());
                        if case.federal_claim_code == 1 && case.provincial_claim_code == 1 {
                            july_claim1.insert(fp.clone());
                            if COMMON_PAY_PERIODS.contains(&case.pay_period) {
                                july_claim1_common.insert(fp);
                            }
                        }
                    } else {
                        july_uncapturable.insert(fp);
                    }
                }
            }
            CaseClass::LogLadder => {
                log_form.insert(fp);
            }
            CaseClass::DateAnchor => {}
        }
    }

    let july_by_province: BTreeMap<String, u64> = july_by_province
        .into_iter()
        .map(|(k, v)| (k, set_len(&v)))
        .collect();

    let july_pdoc_n = set_len(&july_pdoc);
    let july_all_n = set_len(&july_all);
    let july_uncap_n = set_len(&july_uncapturable);

    SamplingReport {
        grid_version: grid.manifest.grid_version.clone(),
        grid_cases: grid.manifest.case_count,
        by_class,
        unresolvable_as_of: unresolvable,
        resolvable,
        boundary_resolvable,
        unique_form_all_resolvable: set_len(&all_form),
        unique_form_log_resolvable: set_len(&log_form),
        unique_form_boundary_ignoring_as_of: set_len(&boundary_form),
        unique_form_boundary_with_rule_set: u64::try_from(boundary_with_edition.len()).unwrap_or(0),
        unique_form_boundary_january: set_len(&january),
        unique_form_boundary_july_all_legal_p: july_all_n,
        unique_form_boundary_july: july_pdoc_n,
        unique_form_boundary_july_uncapturable: july_uncap_n,
        unique_form_boundary_july_claim1: set_len(&july_claim1),
        unique_form_boundary_july_claim1_common_p: set_len(&july_claim1_common),
        unique_form_boundary_july_by_province: july_by_province,
        hours_at_3s_full_grid: hours(grid.manifest.case_count),
        hours_at_3s_unique_form_all: hours(set_len(&all_form)),
        hours_at_3s_unique_boundary_form: hours(set_len(&boundary_form)),
        hours_at_3s_july_boundary: hours(july_pdoc_n),
        hours_at_3s_july_boundary_claim1: hours(set_len(&july_claim1)),
        hours_at_3s_july_boundary_claim1_common_p: hours(set_len(&july_claim1_common)),
        overnight_8h_capacity: 9600,
        cache_records_on_disk: cache_record_count,
        notes: vec![
            "PDOC does not expose as_of, k2_method, targets, or grid id.".to_string(),
            "DateBeforeCoverage (2025-12-31) is an engine error path, not a PDOC form.".to_string(),
            "Live PDOC as of 2026-09 implements the current edition; January BC/NL/PE cannot be recaptured.".to_string(),
            format!(
                "PDOC salary form exposes 10 of 14 legal P; queue is {july_pdoc_n} distinct capturable July forms (fingerprint-deduped). Superseded all-14-P figure was {july_all_n}; uncapturable class holds {july_uncap_n}."
            ),
            "PDOC queue is jurisdiction-sorted (AB, BC, …): early mismatch rate reflects the Alberta block, not the global rate.".to_string(),
            "Many grid cells collapse to one PDOC fingerprint; finished capture count ≤ published distinct-form count.".to_string(),
        ],
    }
}

/// Adopted split (CONFORMANCE.md): capturable July boundary → PDOC; uncapturable
/// boundary (missing P / $0 / sub-dollar) → invariants + differential; interior
/// ladder and date anchors → invariants; unresolvable as_of → engine error.
pub fn oracle_class_for_case(case: &GridCase) -> OracleClass {
    if resolve_edition(&case.as_of).is_none() {
        return OracleClass::EngineError;
    }
    match classify_case(case) {
        CaseClass::Boundary => {
            if is_pdoc_capturable_form(case.pay_period, &case.gross_pay) {
                OracleClass::Pdoc
            } else {
                OracleClass::Uncapturable
            }
        }
        CaseClass::LogLadder | CaseClass::DateAnchor => OracleClass::Invariants,
    }
}

/// Spec §11.4 census: cells by jurisdiction, pay period, rule-set version, oracle class.
pub fn oracle_census(grid: &Grid) -> Vec<CensusRow> {
    let mut counts: BTreeMap<(String, u16, String, OracleClass), u64> = BTreeMap::new();
    for case in &grid.cases {
        let class = oracle_class_for_case(case);
        let edition = resolve_edition(&case.as_of).unwrap_or_else(|| "none".to_string());
        *counts
            .entry((case.province.clone(), case.pay_period, edition, class))
            .or_insert(0) += 1;
    }
    counts
        .into_iter()
        .map(
            |((jurisdiction, pay_period, rule_set_version, oracle_class), cells)| CensusRow {
                jurisdiction,
                pay_period,
                rule_set_version,
                oracle_class,
                cells,
            },
        )
        .collect()
}

/// One queue row for the PDOC harness (July live-edition boundary forms).
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct PdocQueueItem {
    pub rule_set_version: String,
    pub as_of: String,
    pub province: String,
    pub pay_period: u16,
    pub gross_pay: String,
    pub calculation_option: String,
    pub bonus: Option<String>,
    pub federal_claim_code: u8,
    pub provincial_claim_code: u8,
    /// Boundary target prefix used for stratification (e.g. `ympe`).
    pub boundary_class: String,
}

fn boundary_class_of(case: &GridCase) -> String {
    for t in &case.targets {
        for prefix in BOUNDARY_PREFIXES {
            if t.starts_with(prefix) {
                return prefix.trim_end_matches(':').to_string();
            }
        }
    }
    case.targets
        .iter()
        .find(|t| is_boundary_target(t))
        .map(|t| t.split(':').next().unwrap_or(t).to_string())
        .unwrap_or_else(|| "boundary".to_string())
}
fn queue_item(case: &GridCase, edition: &str) -> PdocQueueItem {
    PdocQueueItem {
        rule_set_version: edition.to_string(),
        as_of: case.as_of.clone(),
        province: case.province.clone(),
        pay_period: case.pay_period,
        gross_pay: case.gross_pay.clone(),
        calculation_option: case.calculation_option.clone(),
        bonus: case.bonus.clone(),
        federal_claim_code: case.federal_claim_code,
        provincial_claim_code: case.provincial_claim_code,
        boundary_class: boundary_class_of(case),
    }
}

/// Unique July boundary forms against the ten capturable P — the PDOC queue.
pub fn july_boundary_queue(grid: &Grid) -> Vec<PdocQueueItem> {
    let mut seen: BTreeSet<PdocFingerprint> = BTreeSet::new();
    let mut out = Vec::new();
    for case in &grid.cases {
        if classify_case(case) != CaseClass::Boundary {
            continue;
        }
        let Some(ed) = resolve_edition(&case.as_of) else {
            continue;
        };
        if ed != "2026-07-01" {
            continue;
        }
        if !is_pdoc_capturable_form(case.pay_period, &case.gross_pay) {
            continue;
        }
        let fp = pdoc_fingerprint(case);
        if !seen.insert(fp) {
            continue;
        }
        out.push(queue_item(case, &ed));
    }
    out
}

/// Stratified smoke over the capturable July queue: province × boundary_class
/// coverage, then round-robin fill. Claim 0 included.
pub fn stratified_smoke_queue(grid: &Grid, n: usize) -> Vec<PdocQueueItem> {
    let full = july_boundary_queue(grid);
    if n == 0 || full.is_empty() {
        return Vec::new();
    }

    let mut by_key: BTreeMap<(String, String), Vec<PdocQueueItem>> = BTreeMap::new();
    for item in &full {
        by_key
            .entry((item.province.clone(), item.boundary_class.clone()))
            .or_default()
            .push(item.clone());
    }

    let mut picked: BTreeSet<(String, u16, String, u8, u8, Option<String>)> = BTreeSet::new();
    let mut out: Vec<PdocQueueItem> = Vec::new();

    let take_key = |item: &PdocQueueItem| {
        (
            item.province.clone(),
            item.pay_period,
            item.gross_pay.clone(),
            item.federal_claim_code,
            item.provincial_claim_code,
            item.bonus.clone(),
        )
    };

    let score = |it: &PdocQueueItem| -> (u8, u8) {
        let claim0 = u8::from(it.federal_claim_code == 0 || it.provincial_claim_code == 0);
        let uncommon = u8::from(!COMMON_PAY_PERIODS.contains(&it.pay_period));
        (claim0, uncommon)
    };

    // Pass 1: one per province×boundary_class.
    for ((_prov, _class), mut items) in by_key {
        items.sort_by(|a, b| score(b).cmp(&score(a)));
        if let Some(item) = items.into_iter().next() {
            let k = take_key(&item);
            if picked.insert(k) {
                out.push(item);
            }
        }
        if out.len() >= n {
            return out.into_iter().take(n).collect();
        }
    }

    // Pass 2: round-robin by province; alternate common vs uncommon PDOC P.
    let mut by_prov: BTreeMap<String, Vec<PdocQueueItem>> = BTreeMap::new();
    for item in &full {
        let k = take_key(item);
        if picked.contains(&k) {
            continue;
        }
        by_prov
            .entry(item.province.clone())
            .or_default()
            .push(item.clone());
    }
    for list in by_prov.values_mut() {
        // Stable mix: sort by pay_period then claim so round-robin sees variety.
        list.sort_by(|a, b| {
            a.pay_period
                .cmp(&b.pay_period)
                .then(a.federal_claim_code.cmp(&b.federal_claim_code))
                .then(a.gross_pay.cmp(&b.gross_pay))
        });
    }

    let mut prefer_uncommon = true;
    while out.len() < n {
        let mut progressed = false;
        let provinces: Vec<String> = by_prov.keys().cloned().collect();
        for prov in provinces {
            if out.len() >= n {
                break;
            }
            let Some(list) = by_prov.get_mut(&prov) else {
                continue;
            };
            let idx = list.iter().position(|it| {
                let uncommon = !COMMON_PAY_PERIODS.contains(&it.pay_period);
                if prefer_uncommon {
                    uncommon
                } else {
                    !uncommon
                }
            });
            let idx = idx.or_else(|| if list.is_empty() { None } else { Some(0) });
            if let Some(i) = idx {
                let item = list.remove(i);
                let k = take_key(&item);
                if picked.insert(k) {
                    out.push(item);
                    progressed = true;
                }
            }
        }
        prefer_uncommon = !prefer_uncommon;
        if !progressed {
            break;
        }
    }
    out.into_iter().take(n).collect()
}
